### ISSUE TITLE
dce-downloader's documented staging url for config.json is incorrect

### ISSUE THREAD

**Issue by jlove-bazaarvoice** [bazaarvoice/dce-tools#14]
dce-downloader's staging URL for config.json is documented as `"url" : "https://stg-api.bazaarvoice.com/dce/v3/data"` in both the README and example config file:
- https://github.com/bazaarvoice/dce-tools/blob/6dbae421f50cd70d56df6cb5305bee7fdcfa12ac/code/dce-downloader/README.MD#L21
- https://github.com/bazaarvoice/dce-tools/blob/6dbae421f50cd70d56df6cb5305bee7fdcfa12ac/code/dce-downloader/config.json.example#L6

The staging URL's domain should be **stg.api.bazaarvoice.com**.

**Comment by jerrylawson** [comment]
Change was already in master branch
